# Generated by Django 2.2.4 on 2019-09-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailSettings',
            fields=[
                ('name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('val', models.CharField(max_length=250)),
            ],
        ),
    ]
